 zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    logging:
        driver: "none"

  hbase:
    image: pierrezemb/hbase-docker:standalone-1.3.1
    links:
      - zookeeper
    logging:
      driver: "none"
    ports:
      - "16010:16010"
    expose:
      - "8080"
      - "9090"
      - "16000"
      - "16010"
      - "16020"
      - "16030"
    command: ["/wait-for-it.sh", "zookeeper:2181", "-t", "10", "--", "/usr/bin/supervisord"]
